FROM node:12-alpine

RUN mkdir -p /home/ec2-user/StackMEAN-Burgers/Burgers/node_modules && chown -R node:node /home/ec2-user/StackMEAN-Burgers/Burgers

WORKDIR /home/ec2-user/StackMEAN-Burgers/Burgers

COPY package*.json ./

USER node

RUN npm install

COPY --chown=node:node . .

EXPOSE 3000

CMD [ "node", "src/index.js" ]

